(() => {
  'use strict';

  const CONFIG = { apiUrl: 'https://api.mueblesavenida.com' };
  const STORAGE_KEY = 'mis-tareas-session';
  const state = { session: loadSession(), folders: [], folder: null, tasks: [], loading: false, saveTimers: new Map() };
  const $ = (selector) => document.querySelector(selector);

  function loadSession() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || null; } catch { return null; } }
  function saveSession(session) { state.session = session; localStorage.setItem(STORAGE_KEY, JSON.stringify(session)); }
  function clearSession() { state.session = null; localStorage.removeItem(STORAGE_KEY); }
  function escapeHtml(value = '') { return String(value).replace(/[&<>'"]/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c])); }
  function api(path, options = {}) {
    const headers = { 'Content-Type': 'application/json', ...(options.headers || {}) };
    if (state.session?.access_token) headers.Authorization = `Bearer ${state.session.access_token}`;
    return fetch(`${CONFIG.apiUrl}${path}`, { ...options, headers }).then(async (response) => {
      const body = await response.json().catch(() => ({}));
      if (!response.ok) { const error = new Error(body?.errors?.[0]?.message || `Error ${response.status}`); error.status = response.status; throw error; }
      return body.data ?? body;
    });
  }
  async function refreshToken() {
    if (!state.session?.refresh_token) return false;
    try { const data = await fetch(`${CONFIG.apiUrl}/auth/refresh`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ refresh_token:state.session.refresh_token, mode:'json' }) }).then(r => r.json()); if (!data.data) return false; saveSession(data.data); return true; } catch { return false; }
  }
  async function withAuth(request) { try { return await request(); } catch (error) { if (error.status === 401 && await refreshToken()) return request(); if (error.status === 401) { clearSession(); showLogin(); } throw error; } }
  function setBusy(button, busy, label = 'Cargando…') { if (!button) return; if (busy) { button.dataset.label = button.innerHTML; button.innerHTML = label; button.disabled = true; } else { button.innerHTML = button.dataset.label || button.innerHTML; button.disabled = false; } }
  function showLogin() { $('#login-view').hidden = false; $('#workspace-view').hidden = true; $('#email').focus(); }
  function showWorkspace() { $('#login-view').hidden = true; $('#workspace-view').hidden = false; $('#user-email').textContent = state.session?.user?.email || ''; route(); }
  function notify(message, error = false) { const toast = $('#toast'); toast.textContent = message; toast.className = `toast${error ? ' error' : ''}`; toast.hidden = false; setTimeout(() => { toast.hidden = true; }, 3500); }
  function errorView(message, retry) { return `<div class="empty-state"><strong>Algo no ha ido bien</strong><span>${escapeHtml(message)}</span><br><button class="retry-button" data-action="retry">Reintentar</button></div>`; }

  async function login(event) { event.preventDefault(); const form = event.currentTarget, button = form.querySelector('button[type=submit]'), error = $('#login-error'); error.hidden = true; setBusy(button, true, 'Entrando…'); try { const data = await fetch(`${CONFIG.apiUrl}/auth/login`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ email:form.email.value.trim(), password:form.password.value }) }).then(async r => { const body=await r.json().catch(()=>({})); if(!r.ok) throw new Error(body?.errors?.[0]?.message || 'No se pudo iniciar sesión'); return body.data; }); saveSession(data); const me = await api('/users/me?fields=id,email'); state.session.user = me; saveSession(state.session); showWorkspace(); } catch (e) { error.textContent = e.message.includes('Invalid') ? 'El correo o la contraseña no son correctos.' : 'No se pudo conectar con el servidor. Inténtalo de nuevo.'; error.hidden = false; } finally { setBusy(button, false); } }
  async function loadFolders() { state.loading = true; renderFolders(); try { state.folders = await withAuth(() => api('/items/carpetas_tareas?filter[eliminada][_eq]=false&filter[user_created][_eq]=%24CURRENT_USER&fields=id,nombre,date_created&sort=-date_created')); renderFolders(); } catch (e) { $('#workspace-content').innerHTML = errorView(e.message, loadFolders); } finally { state.loading = false; } }
  function renderFolders() { $('#workspace-content').innerHTML = `<div class="page-header"><div><p class="eyebrow">TU ORGANIZACIÓN</p><h2>Mis carpetas</h2><p>Todo lo que tienes en marcha, en un mismo lugar.</p></div><button class="primary-button" data-action="new-folder"><span>+ Nueva carpeta</span></button></div><p class="section-label">${state.folders.length ? 'CARPETAS ACTIVAS' : 'EMPIEZA POR AQUÍ'}</p><div class="folder-grid">${state.loading ? '<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>' : state.folders.map(folderCard).join('')}${!state.loading && state.folders.length ? '<button class="add-card" data-action="new-folder">+ Añadir carpeta</button>' : !state.loading ? '<div class="empty-state"><strong>Aún no tienes carpetas</strong><span>Crea una para empezar a ordenar tus tareas.</span><br><button class="retry-button" data-action="new-folder">Crear mi primera carpeta</button></div>' : ''}</div>`; }
  function folderCard(folder) { return `<article class="folder-card"><a class="folder-link" href="#folder/${encodeURIComponent(folder.id)}"><div class="folder-icon" aria-hidden="true"></div><div class="folder-name">${escapeHtml(folder.nombre)}</div><div class="folder-meta">Abrir carpeta →</div></a><div class="card-actions"><button class="mini-button" title="Renombrar" aria-label="Renombrar ${escapeHtml(folder.nombre)}" data-action="rename-folder" data-id="${folder.id}">✎</button><button class="mini-button" title="Eliminar" aria-label="Eliminar ${escapeHtml(folder.nombre)}" data-action="delete-folder" data-id="${folder.id}">×</button></div></article>`; }
  async function createFolder() { const name = prompt('Nombre de la nueva carpeta:'); if (!name?.trim()) return; try { await withAuth(() => api('/items/carpetas_tareas', { method:'POST', body:JSON.stringify({ nombre:name.trim(), eliminada:false }) })); notify('Carpeta creada'); await loadFolders(); } catch(e) { notify(e.message, true); } }
  async function renameFolder(id) { const folder = state.folders.find(item => item.id === id); const name = prompt('Nuevo nombre:', folder?.nombre || ''); if (!name?.trim() || name.trim() === folder?.nombre) return; try { await withAuth(() => api(`/items/carpetas_tareas/${id}`, { method:'PATCH', body:JSON.stringify({ nombre:name.trim() }) })); notify('Carpeta renombrada'); await loadFolders(); } catch(e) { notify(e.message, true); } }
  async function deleteFolder(id) { const folder = state.folders.find(item => item.id === id); if (!folder || !confirm(`¿Eliminar “${folder.nombre}”? Sus tareas también se archivarán.`)) return; try { await withAuth(() => api(`/items/carpetas_tareas/${id}`, { method:'PATCH', body:JSON.stringify({ eliminada:true }) })); notify('Carpeta eliminada'); await loadFolders(); } catch(e) { notify(e.message, true); } }
  async function loadFolder(id) { state.folder = state.folders.find(f => f.id === id) || { id, nombre:'Carpeta' }; state.loading = true; renderFolder(); try { state.tasks = await withAuth(() => api(`/items/tareas?filter[eliminada][_eq]=false&filter[user_created][_eq]=%24CURRENT_USER&filter[carpeta][_eq]=${encodeURIComponent(id)}&filter[carpeta][user_created][_eq]=%24CURRENT_USER&fields=id,titulo,descripcion,completada,date_created&sort=-date_created`)); renderFolder(); } catch(e) { $('#workspace-content').innerHTML = errorView(e.message, () => loadFolder(id)); } finally { state.loading = false; } }
  function renderFolder() { const pending = state.tasks.filter(t => !t.completada), done = state.tasks.filter(t => t.completada); $('#workspace-content').innerHTML = `<a class="back-link" href="#folders">← Todas las carpetas</a><div class="folder-heading"><div class="folder-icon" aria-hidden="true"></div><div><p class="eyebrow">CARPETA</p><h2>${escapeHtml(state.folder.nombre)}</h2></div></div><form id="new-task-form" class="new-task"><input class="new-task-input" name="title" placeholder="¿Qué necesitas hacer?" aria-label="Título de la nueva tarea" required /><button class="primary-button" type="submit"><span>Añadir tarea</span><span aria-hidden="true">↗</span></button></form><div class="task-columns"><section><h3 class="task-column-title"><span class="dot"></span>Pendientes <span class="count">${pending.length}</span></h3><div class="task-list">${state.loading ? '<div class="empty-state">Cargando tareas…</div>' : pending.length ? pending.map(taskCard).join('') : '<div class="empty-state"><strong>Todo despejado</strong><span>No tienes tareas pendientes.</span></div>'}</div></section><section><h3 class="task-column-title"><span class="dot green"></span>Completadas <span class="count">${done.length}</span></h3><div class="task-list">${state.loading ? '' : done.length ? done.map(taskCard).join('') : '<div class="empty-state"><span>Aquí aparecerán tus tareas terminadas.</span></div>'}</div></section></div>`; }
  function taskCard(task) { return `<article class="task-card ${task.completada ? 'done' : ''}" data-task-id="${task.id}"><div class="task-summary"><button class="complete-toggle" data-action="toggle-completed" type="button" aria-label="Marcar como ${task.completada ? 'pendiente' : 'completada'}"><span class="check-box" aria-hidden="true">${task.completada ? '✓' : ''}</span></button><button class="task-title-button" data-action="toggle-task" type="button" aria-expanded="false"><span class="task-title">${escapeHtml(task.titulo)}</span><span class="chevron" aria-hidden="true">⌄</span></button></div><div class="task-editor" hidden><input data-field="titulo" value="${escapeHtml(task.titulo)}" aria-label="Título" /><textarea data-field="descripcion" placeholder="Añade una descripción…" aria-label="Descripción">${escapeHtml(task.descripcion || '')}</textarea><div class="editor-footer"><span class="save-status" data-status>Guardado</span><button class="danger-button" data-action="delete-task" type="button">Eliminar tarea</button></div></div></article>`; }
  async function createTask(form) { const title=form.title.value.trim(); if(!title) return; const button=form.querySelector('button'); setBusy(button,true,'Añadiendo…'); try { await withAuth(() => api('/items/tareas', {method:'POST',body:JSON.stringify({titulo:title,carpeta:state.folder.id,completada:false,eliminada:false})})); form.reset(); notify('Tarea añadida'); await loadFolder(state.folder.id); } catch(e) { notify(e.message,true); } finally { setBusy(button,false); } }
  async function saveTask(taskId, patch, status) { clearTimeout(state.saveTimers.get(taskId)); status.textContent='Guardando…'; status.className='save-status saving'; state.saveTimers.set(taskId,setTimeout(async()=>{ try { await withAuth(() => api(`/items/tareas/${taskId}`,{method:'PATCH',body:JSON.stringify(patch)})); status.textContent='Guardado'; status.className='save-status saved'; setTimeout(()=>{status.className='save-status';},1200); } catch(e) { status.textContent='Error al guardar'; status.className='save-status error'; notify('No se pudo guardar la tarea',true); } },550)); }
  async function deleteTask(card) { const id=card.dataset.taskId; if(!confirm('¿Eliminar esta tarea?')) return; try { await withAuth(() => api(`/items/tareas/${id}`,{method:'PATCH',body:JSON.stringify({eliminada:true})})); notify('Tarea eliminada'); await loadFolder(state.folder.id); } catch(e) { notify(e.message,true); } }
  function route() { const match=location.hash.match(/^#folder\/(.+)$/); if(match) loadFolder(decodeURIComponent(match[1])); else loadFolders(); }
  document.addEventListener('submit', (event) => { if(event.target.id==='login-form') login(event); if(event.target.id==='new-task-form') { event.preventDefault(); createTask(event.target); } });
  document.addEventListener('click', (event) => { const target=event.target.closest('[data-action]'); if(!target) return; const action=target.dataset.action; if(action==='new-folder') createFolder(); if(action==='rename-folder') renameFolder(target.dataset.id); if(action==='delete-folder') deleteFolder(target.dataset.id); if(action==='retry') route(); if(action==='logout'){clearSession();showLogin();} if(action==='delete-task') deleteTask(target.closest('.task-card')); if(action==='toggle-completed'){const card=target.closest('.task-card'), completed=!card.classList.contains('done'), status=card.querySelector('[data-status]'); card.classList.toggle('done',completed); card.querySelector('.check-box').textContent=completed?'✓':''; saveTask(card.dataset.taskId,{completada:completed},status); setTimeout(()=>loadFolder(state.folder.id),700);} if(action==='toggle-task'){const card=target.closest('.task-card'), editor=card.querySelector('.task-editor'), open=editor.hidden; editor.hidden=!open; card.classList.toggle('open',open); target.setAttribute('aria-expanded',open); if(open) editor.querySelector('[data-field=titulo]').focus();} });
  document.addEventListener('input', (event) => { const field=event.target.dataset.field; if(!field) return; const card=event.target.closest('.task-card'), status=card.querySelector('[data-status]'); saveTask(card.dataset.taskId,{[field]:event.target.value},status); });
  document.addEventListener('change', (event) => { if(event.target.dataset.field==='completada') saveTask(event.target.closest('.task-card').dataset.taskId,{completada:event.target.checked},event.target.closest('.task-card').querySelector('[data-status]')); });
  $('#toggle-password').addEventListener('click', () => { const input=$('#password'); input.type=input.type==='password'?'text':'password'; });
  $('#logout-button').dataset.action='logout'; window.addEventListener('hashchange', route);
  if(state.session) withAuth(() => api('/users/me?fields=id,email')).then(me => { state.session.user=me; saveSession(state.session); showWorkspace(); }).catch(() => { clearSession(); showLogin(); }); else showLogin();
})();
